version: "3.9"

services:
  portal:
    build: .
    environment:
      DB_URL: "postgresql://dirtviz:password@postgresql/dirtviz"
      BOKEH_ALLOW_WS_ORIGIN: "localhost:5006"
    ports:
      - "5006:5006"
    depends_on:
      - postgresql
    networks:
      default:

  postgresql:
    image: postgres:14.4
    environment:
      POSTGRES_USER: dirtviz
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgresqldata:/var/lib/postgresql/data
    networks:
      default:
    deploy:
      resources:
        limits:
          memory: 4g
        reservations:
          memory: 3g

  adminer:
    image: adminer
    ports:
      - "8060:8080"
    networks:
      default:

networks:
  default:

volumes:
  postgresqldata:
