version: "3.9"

services:
  http-integration:
    build: .
    environment:
      DB_URL: "postgresql://dirtviz:password@postgresql/dirtviz"
    command: ["python", "-m", "dirtviz.integrations.api"]
    expose:
      - "8090"
    depends_on:
      - postgresql
    networks:
      default:
