version: "3.9"

services:
  http-integration:
    build: .
    restart: always
    environment:
      DB_URL: "postgresql://dirtviz:password@postgresql/dirtviz"
    command: ["python", "-m", "dirtviz.integrations.http"]
    ports:
      - 8090:8090
    depends_on:
      - postgresql
    networks:
      default:
      chirpstack:

networks:
  chirpstack:
    name: "chirpstack-external"
    external: true
