version: "3.9"

services:
  portal:
    build: .
    restart: always
    environment:
      DB_URL: "postgresql://dirtviz:password@postgresql/dirtviz"
      BOKEH_ALLOW_WS_ORIGIN: "localhost:5006"
    ports:
      - 5006:5006
    depends_on:
      - postgresql

  http-integration:
    build: .
    restart: always
    environment:
      DB_URL: "postgresql://dirtviz:password@postgresql/dirtviz"
    command: ["python", "-m", "dirtviz.integrations.http"]
    ports:
      - 8090:8090
    depends_on:
      - postgresql

  postgresql:
    image: postgres:14.4
    restart: always
    environment:
      POSTGRES_USER: dirtviz
      POSTGRES_PASSWORD: password
    volumes:
      - postgresqldata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8060:8080

volumes:
  postgresqldata:
