version: "3.9"

services:
  http-api:
    image: ghcr.io/jlab-sensing/dirtviz:main
    restart: always
    environment:
      DB_URL: "postgresql://dirtviz:password@postgresql/dirtviz"
    command: ["python", "-m", "dirtviz.integrations.api"]
    ports:
      - "8090:8090"
    expose:
      - "8090"
    depends_on:
      - postgresql
    networks:
      default:
