version: "3.9"

services:
  portal:
    build: .
    restart: always
    environment:
      DB_URL: "postgresql://dirtviz:password@portal-postgresql/dirtviz"
      BOKEH_ALLOW_WS_ORIGIN: "localhost:5006"
    ports:
      - 5006:5006
    links:
      - portal-postgresql
    depends_on:
      - portal-postgresql

  portal-http-integration:
    build: .
    restart: always
    environment:
      DB_URL: "postgresql://dirtviz:password@portal-postgresql/dirtviz"
    command: ["python", "-m", "dirtviz.integrations.http"]
    ports:
      - 8090:8090
    links:
      - portal-postgresql
    depends_on:
      - portal-postgresql

  portal-postgresql:
    image: postgres:14.4
    restart: always
    environment:
      POSTGRES_USER: dirtviz
      POSTGRES_PASSWORD: password
    volumes:
      - portal-postgresqldata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8060:8080

  chirpstack-network-server:
    image: chirpstack/chirpstack-network-server:3
    volumes:
      - ./chirpstack-docker/configuration/chirpstack-network-server:/etc/chirpstack-network-server
    depends_on:
      - chirpstack-postgresql
      - mosquitto

  chirpstack-application-server:
    image: chirpstack/chirpstack-application-server:3
    ports:
      - 8080:8080
    volumes:
      - ./chirpstack-docker/configuration/chirpstack-application-server:/etc/chirpstack-application-server
    depends_on:
      - chirpstack-network-server

  chirpstack-gateway-bridge:
    image: chirpstack/chirpstack-gateway-bridge:3
    ports:
      - 1700:1700/udp
    volumes:
      - ./chirpstack-docker/configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
    depends_on: 
      - mosquitto

  chirpstack-postgresql:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - ./chirpstack-docker/configuration/postgresql/initdb:/docker-entrypoint-initdb.d
      - chirpstack-postgresqldata:/var/lib/postgresql/data

  redis:
    image: redis:5-alpine
    volumes:
      - chirpstack-redisdata:/data

  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - 1883:1883
    volumes: 
      - ./chirpstack-docker/configuration/eclipse-mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

volumes:
  portal-postgresqldata:
  chirpstack-postgresqldata:
  chirpstack-redisdata:
