version: "3.9"

services:
  portal:
    build: .
    environment:
      DB_URL: "postgresql://dirtviz:password@postgresql/dirtviz"
      BOKEH_ALLOW_WS_ORIGIN: "localhost:5006"
    ports:
      - "5006:5006"
    depends_on:
      - postgresql

  postgresql:
    image: postgres:14.4
    environment:
      POSTGRES_USER: dirtviz
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgresqldata:/var/lib/postgresql/data
    networks:
      default:
    deploy:
      resources:
        limits:
          memory: 4g
        reservations:
          memory: 3g

  adminer:
    image: adminer
    ports:
      - "8060:8080"

  http-integration:
    build: .
    environment:
      DB_URL: "postgresql://dirtviz:password@postgresql/dirtviz"
    command: ["python", "-m", "dirtviz.integrations.cs_http"]
    expose:
      - "8100"
    depends_on:
      - postgresql

  http-api:
    build: .
    environment:
      DB_URL: "postgresql://dirtviz:password@postgresql/dirtviz"
    command: ["python", "-m", "dirtviz.integrations.api"]
    expose:
      - "8090"
    depends_on:
      - postgresql

volumes:
  postgresqldata:
