version: "3.9"

services:
  http-integration:
    build: .
    environment:
      DB_URL: "postgresql://dirtviz:password@postgresql/dirtviz"
    command: ["python", "-m", "dirtviz.integrations.cs_http"]
    expose:
      - "8090"
    depends_on:
      - postgresql
    networks:
      default:
      chirpstack:

networks:
  chirpstack:
    name: "chirpstack-external"
    external: true
