name: Build and Test

on:
  push:
  pull_request:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        cache: 'pip'

    - name: Install dependencies
      run: pip install -r requirements.txt -r requirements-dev.txt

    - name: Lint
      run: pylint dirtviz

  test:
    timeout-minutes: 1
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        cache: 'pip'

    - name: Start webserver
      run: bokeh serve dirtviz &

    - name: Wait for webserver to start
      run: sleep 10s
      shell: bash

    - name: Run local k6 test
      uses: grafana/k6-action@v0.2.0
      with:
        filename: tests/basic.js
