name: Delete deployment

on:
  delete:
    branches-ignore:
      - main
  workflow_dispatch:

jobs:
  delete_resources:
    runs-on: ubuntu-latest
    if: ${{ github.ref_type == 'branch' }}
    environment: ${{ github.ref_name }}

    steps:
      - name: Setup SSH
        shell: bash
        env:
          SERVER_SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SERVER_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "$SERVER_SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Generate destroy.sql
        uses: cuchi/jinja2-action@v1.2.0
        with:
          template: sql/destroy.sql.j2
          output_file: sql/destroy.sql

      - name: Remove k8s resources
        shell: bash
        run: |
          ssh ${{ secrets.USER }}@${{ secrets.HOSTNAME }} \
          /snap/bin/microk8s kubectl \
          delete all -l git-branch=$GITHUB_REF_NAME -n dirtviz

      - name: Remove database
        shell: bash
        run: |
          cat sql/destroy.sql | \
          ssh ${{ secrets.USER }}@${{ secrets.HOSTNAME }} \
          psql -U ${{ secrets.DB_USER }} -d ${{ github.ref_name }}

      - name: 
        uses: strumwolf/delete-deployment-environment@v2
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            environment: ${{ github.ref_name }}
