name: Lint and Test

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: 'pip'

    - name: Install dependencies
      run: pip install -r requirements.txt -r requirements-dev.txt

    - name: Lint
      run: pylint dirtviz

  test:
    runs-on: ubuntu-latest
    env:
      DB_URL: "postgresql://dirtviz:password@localhost/dirtviz"

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: 'pip'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Start postgresql service
      run: docker compose up postgresql -d

    - name: Start webserver
      run: ./migrate_and_start.sh >> dirtviz_log &

    - name: Wait for webserver to start
      run: sleep 10s
      shell: bash
    
    - name: Import example data
      run: python import_example_data.py

    - name: Run local k6 test
      uses: grafana/k6-action@v0.2.0
      with:
        filename: tests/basic.js

    - name: Echo runtime log
      run: cat dirtviz_log

    - name: Upload log artifact
      uses: actions/upload-artifact@v3
      with:
        name: DirtViz Portal Logs
        path: dirtviz_log
