name: Lint and Test

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: 'pip'

    - name: Install dependencies
      run: pip install -r requirements.txt -r requirements-dev.txt

    - name: Lint
      run: pylint dirtviz

  test:
    runs-on: ubuntu-latest
    env:
      DB_URL: "postgresql://dirtviz:password@localhost/dirtviz"

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: 'pip'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Start postgresql service
      run: docker compose up postgresql -d

    - name: Wait for db to start
      run: sleep 5s

    - name: Apply migrations
      run: alembic -c dirtviz/db/alembic.ini upgrade head

    - name: Import example data
      run: python import_example_data.py

    - name: Start webserver
      run: bokeh serve dirtviz > dirtviz_log 2>&1 &

    - name: Send GET request
      run: curl --connect-timeout 10 http://localhost:5006/dirtviz

    - name: Echo runtime log
      run: cat dirtviz_log

    - name: Upload log artifact
      uses: actions/upload-artifact@v3
      with:
        name: DirtViz Portal Logs
        path: dirtviz_log
